# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Robert Lennon
title: Linguistics Researcher
email: r.w.lennon@lancaster.ac.uk
website: robertlennon50.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: robertlennon50
github_username:  robertlennon50
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: robert-lennon
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: ResearchGate link
  icon: fas fa-globe
  url: https://www.researchgate.net/profile/Robert_Lennon4
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Linguistics Researcher at the [Phonetics Lab](http://wp.lancs.ac.uk/phonetics/) at [Lancaster University](https://www.lancaster.ac.uk/). My research is in sociolinguistics, phonetics and speech perception, and I'm interested in how the social aspects of speech communities affect how speech sounds are produced and perceived.
  
  My expertise is in Scottish English (especially phonetic variation in Glasgow), rhoticity, and cross-dialect perception. I also have some knowledge of perception of speech tempo and phonetic reduction.

  I am most skilled in: <mark>Sociolinguistics teaching</mark>, <mark>R</mark>, <mark>Praat</mark> and <mark>Perception experiments</mark>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Changing /r/ Accents
#        link: [Project website](http://www.research.lancs.ac.uk/portal/en/upmprojects/changing-r-accents-towards-a-sociophonological-understanding-of-sound-change(c932501b-8414-4b09-85b6-61b890689fe1).html)
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PhD Linguistics
        #caption: 2019
        sub_title: University of Glasgow, 2019
        #quote: >
        #  Supervisors: [Dr Rachel Smith](https://www.gla.ac.uk/schools/critical/staff/rachelsmith/), [Professor Jane Stuart-Smith](https://www.gla.ac.uk/schools/critical/staff/janestuart-smith/)
        description: | # this will include new lines to allow paragraphs
          Thesis title: [Experience and Learning in Cross-dialect perception: Derhoticised /r/ in Glasgow](http://theses.gla.ac.uk/74370/)

      - layout: left
        title: MSc Linguistics
        #caption: 2013
        sub_title: University of Glasgow, 2013
        #quote: >
        #  Supervisors: Dr Rachel Smith, Professor Jane Stuart-Smith
        description: | # this will include new lines to allow paragraphs
          Thesis title: The effect of experience in cross-dialect perception: Parsing /r/ in Glaswegian

      - layout: left
        title: MA English Language
        #caption: 2012
        sub_title: University of Glasgow, 2012
        #quote: >
        #  Supervisors: Dr Rachel Smith, Professor Jane Stuart-Smith
        description: | # this will include new lines to allow paragraphs
          Dissertation title: A real-time sociophonetic study of postvocalic /r/ in the speech of schoolchildren in Bearsden



  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research Associate
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Lancaster University
        caption: *2020 - present*
        #quote: >
        #  Changing /r/ accents? Towards a sociophonological understanding of sound change.
        description: | # this will include new lines to allow paragraphs
            **Changing /r/ accents? Towards a sociophonological understanding of sound change.**
            
            We're using a variety of methods to investigate residual rhoticity in Blackburn, Lancashire (where many speakers still pronounce the /r/ in e.g. 'car', 'third'), examining the mechanisms by which it is changing over time.

      - layout: left
        title: Research Fellow
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: University of Leeds
        caption: *2017 - 2020*
        #quote: >
        #  Changing /r/ accents? Towards a sociophonological understanding of sound change.
        description: | # this will include new lines to allow paragraphs
            **Speech tempo perception and missing sounds.**
            
            In this project we investigated the link between laboratory measurements of speech tempo and how listeners perceive speaking rate. I designed and ran a suite of speech perception experiments, maintained a large phonetically-aligned corpus, and contributed to analysis, conference presentations and journal submissions.


#![Visitor Count](https://profile-counter.glitch.me/robertlennon50.github.io/count.svg)

#<img src="https://hitcounter.pythonanywhere.com/count/tag.svg" alt="Hits">

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#      
#      Look at this cool image of Scottish mountains
#      
#      ![Mountains](/images/Isle_of_Skye_Scotland.jpg "Mountains")

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
